version: "3"
networks:
  leaveform_network:
volumes:
  leaveform_volume:
services:

  db:
    build:
      context: ./leave_api
      dockerfile: db.dockerfile
    ports:
      - "5400:5432"
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: shamy@123
    networks:
      - leaveform_network
    volumes:
      - leaveform_volume:/var/lib/postgresql/data

  backend:
    build:
      context: ./leave_api
      dockerfile: dockerfile
    ports:
      - "8086:8086"
    networks:
      - leaveform_network
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "4200:4200"
    networks:
      - leaveform_network
    depends_on:
      - backend
